- path: "/github"
  url: "https://github.com/iamargus95"
- path: "/personal"
  url: "https://iamargus95.github.io/"
- path: "/resume"
  url: "https://iamargus95.github.io/assets/documents/Suraj_Kamath.pdf"